dataset:
  train_path: 'DL_Bradford/data/processed/train/stratified_train.csv'
  val_path: "DL_Bradford/data/processed/val/V12_feat_val.csv"
  test_path: "DL_Bradford/data/processed/test/V12_UK_feat_pred.txt"
  # test_path: "DL_Bradford/data/processed/test/stratified_test.csv"
  raw_path: "DL_Bradford/data/raw/test/V12_UK_feat_pred.txt"
  batch_size: 64

augmentation:
  enabled: true
  augmentations:
    # - type: 'random_rotation'
    #   axis: 'z'
    #   angle_range: [-180, 180]
    - type: 'random_jitter'
      std: 0.01
    - type: 'random_scale'
      scale_range: [0.8, 1.2]
    - type: 'random_dropout'
      drop_rate: 0.3
