dataset:
  train_path: 'data/processed/train/V12_feat_train.txt'
  val_path: "data/processed/val/V12_feat_val.txt"
  test_path: "data/processed/test/V12_feat_test.txt"
  batch_size: 16

augmentation:
  enabled: true
  augmentations:
    # - type: 'random_rotation'
    #   axis: 'z'
    #   angle_range: [-180, 180]
    - type: 'random_jitter'
      std: 0.01
    - type: 'random_scale'
      scale_range: [0.8, 1.2]
    - type: 'random_dropout'
      drop_rate: 0.3
