dataset:
  train_path: 'data/processed/train/train.csv'
  val_path: "data/processed/val/validation.csv"
  test_path: "data/processed/test/V12_UK_dropNaN_pred_processed.txt"
  # test_path: "data/processed/test/test.csv"
  raw_path: "data/raw/test/V12_UK_dropNaN_pred.txt"            
  batch_size: 256

augmentation:
  enabled: true
  augmentations:
    # - type: 'random_rotation'
    #   axis: 'z'
    #   angle_range: [-180, 180]
    - type: 'random_jitter'
      std: 0.01
    - type: 'random_scale'
      scale_range: [0.8, 1.2]
    - type: 'random_dropout'
      drop_rate: 0.3
